### PR TITLE
Fix invalid todo markup (spec was still run for libsass)

### PR DESCRIPTION
**Pull request by mgreter**

### CODE REVIEW

**Review by jathak — APPROVED** [review]

**Comment by stof** [comment]
this looks like an issue of the libsass runner (or maybe of the ruby runner). This YAML is equivalent (and is the one produced by the interactive mode when writing the file with the ts runner)

**Comment by nex3** [comment]
I believe Ruby's YAML implementation interprets `:foo:` as a Symbol key but `':foo':` as a String key.

**Comment by stof** [comment]
then, the interactive mode for the ts runner should be fixed to dumping it unquoted or the ruby runner should be updated to support string keys

**Comment by nex3** [comment]
Yep: https://github.com/sass/sass-spec/issues/1649

**Pull request merged**
