### PR TITLE
Enable LibSass specs for hex colors with alpha

### PR DESCRIPTION
**Pull request by xzyfer**
[skip libsass]

### CODE REVIEW

**Comment by nex3** [comment]
@xzyfer Can you delete [LibSass-specific files](https://github.com/xzyfer/sass-spec/blob/70a653dade9d9cac5508a3fcc6dd1508c70d9323/spec/values/colors/alpha_hex/deprecation/error-libsass) when marking a spec as ignored for LibSass?

**Comment by xzyfer** [comment]
Yep, sorry

**Comment by nex3** [comment]
Also, it looks like this broke Travis: https://travis-ci.org/sass/sass-spec/builds/408503694

**Comment by xzyfer** [comment]
Looks like Travis may not be pulling in the latest sassc. Libsasy defaults
to precision 5 where it looks like dart sass and ruby sass default to 10

**Comment by nex3** [comment]
The default precision shouldn't matter; the engine sets the precision explicitly.

**Comment by xzyfer** [comment]
I'm not sure what I'm missing then.

https://github.com/sass/sass-spec/blob/78b0f9aca1b858b6f816b90c501248c82a3a5847/lib/sass_spec/test_case.rb#L79-L81

The default appears to be 5. I don't it being set otherwise in any relevant options.yml. Yet the output in the specs appears to use precision 10.

**Comment by nex3** [comment]
Since no other implementation is generating the wrong precision here, it seems like it might be a LibSass bug. Can you roll back this PR while you investigate to get the build green?

**Comment by nex3** [comment]
Oh I see what's happening here--I generated the expected test cases using Dart Sass, which always uses precision 10.

**Pull request merged**
