### PR TITLE
Add specs for issue 1578

### PR DESCRIPTION
**Pull request by xzyfer**
This PR add specs for sass/libsass#1578

### CODE REVIEW

**Comment by xzyfer** [comment]
@saper looks like a possible bug in sass-spec.

**Comment by saper** [comment]
Strange. When I generated the test (with `-c path/to/ruby/sass`) it didn't produce any warning and there was no `error` file. 

I was using Sass 3.4.14.2e0f33b (Selective Steve)

How did you get that warning?

**Comment by saper** [comment]
https://github.com/xzyfer/sass-spec/pull/1

**Comment by xzyfer** [comment]
Thanks @saper applied your patch in 51c7469.

I think the root cause of why this happened is because the --nuke flag is not idempotent anymore https://github.com/sass/sass-spec/issues/533

**Pull request merged**
