### PR TITLE
Add spec for css empty namespace attribute selector

### PR DESCRIPTION
**Pull request by pjeweb**
see sass/sass#3199 [skip dart-sass]

### CODE REVIEW

**Comment by stof** [comment]
This PR should have `[skip dart-sass]` in its description, to avoid running the CI against the unpatched dart-sass version, as described in https://github.com/sass/dart-sass/blob/main/CONTRIBUTING.md#changing-the-language

**Comment by pjeweb** [comment]
The skip tag should be added now?!

**Comment by stof** [comment]
@pjeweb yeah, things look good now. You just need to wait for a maintainer to approve the workflow run, as you are a first-time contributor (I'm not a maintainer, only a contributor, so I cannot approve it myself)

**Review by nex3 — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
