### PR TITLE
Test all output styles

### PR DESCRIPTION
**Pull request by mgreter**
Related to https://github.com/sass/libsass/pull/910 and https://github.com/sass/sassc/pull/97

- Adds expected files for all output styles
- Changes test runner to test all output styles
- Added flag files to skip or clean certain tests

### CODE REVIEW

**Comment by xzyfer** [comment]
Could you please update the `nuke` code to produce all these new spec files?

**Comment by mgreter** [comment]
By the way, quite a few todo tests emit this warning in ruby sass:
```
The subject selector operator "!" is deprecated and will be removed in a future release.
This operator has been replaced by ":has()" in the CSS spec.
```

I wonder if we want to update those tests and if we even want to implement the deprecated syntax?

**Comment by xzyfer** [comment]
We should continue to support those specs until Ruby Sass starts to throw an error. Other wise we're not a drop in replacement.

**Comment by xzyfer** [comment]
Also fixes https://github.com/sass/sass-spec/issues/247

**Comment by mgreter** [comment]
Added PR to my own branch for https://github.com/sass/libsass/issues/922
https://github.com/mgreter/sass-spec/pull/1

**Comment by mgreter** [comment]
IMO we should get a decision if we want to merge this PR before releasing libsass 3.2!
Since it is a pretty big change I would like to have some feedback before merging it on my own!
//CC @chriseppstein @hcatlin @akhleung @xzyfer @am11

**Comment by xzyfer** [comment]
IMO this is definitely worth doing, especially if all these specs are currently passing on 3.2!

As long the utility methods (nuke, unexpected-pass) function correctly then this gets a :+1:  from me.

The one possible concern could the significantly increased running time of Ruby Sass if they were to switch to sass-spec sometime in the future?

It's worth noting it's likely that sass-spec will undergo significant changes with @chriseppstein's work as per https://github.com/sass/sass-spec/issues/82#issuecomment-69998072.

**Comment by am11** [comment]
:+1:
@mgreter, (at least on http://sassmeister.com/) it seems like ruby sass has default output style set to expanded. Should we do the same here (and then all the down-streams will follow)? 

This (breaking) change will be the perfect candidate for forthcoming major version of node-sass.

//cc @jedfoster.

**Comment by mgreter** [comment]
IMO the nuke option etc. should still work, since it only adds more tests with different output options and expected output path. But I actually never did any ruby before these changes to the spec runner. So I really would like to get a O.K. from a someone that knows ruby.

The running time to run the spec test might be an issue, but IMO it's worth it. My perl-libsass spec runner needs 15s-20s to do all 4044 checks (including todo test). Regenerating all 4044 spec test via ruby sass takes about 3 minutes, while exhausting all my [4 cores] [1] (i7-3770).

It will probably also increase the coverage by one or two percent (I would guess)!

[1]: https://github.com/sass/perl-libsass/blob/latest/t/99_sass_specs.t#L149

**Pull request merged**
