### PR TITLE
Support TODOs in interactive mode.

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Comment by nschonni** [comment]
It would probably be good to update the README after you finish changing all these. Or maybe add a docs folder

**Comment by nex3** [comment]
As far as I can tell, there isn't really any pre-existing documentation for anything around `--interactive` mode that I could update, and I don't really have time at the moment to write it from scratch.

**Comment by nschonni** [comment]
This one would probalby be under https://github.com/sass/sass-spec#pending-todo-tests

**Comment by nex3** [comment]
It already mentions it, even though it wasn't supported before:

> The `--interactive` mode will provide marking a test as pending for the current implementation as a remedy for many types of spec failures.

**Pull request merged**
