### PR TITLE
 Add todo spec test for libsass issue 2863 

### PR DESCRIPTION
**Pull request by mgreter**
https://github.com/sass/libsass/issues/2863

### CODE REVIEW

**Comment by nex3** [comment]
Even though [the new style guide](https://github.com/sass/sass-spec/blob/88f4ef08a606792656ddb79c4855472e75822881/STYLE_GUIDE.md) hasn't officially landed yet, please follow it when adding any new specs.

**Comment by mgreter** [comment]
@nex3 can you elaborate where I got it wrong?

**Comment by glebm** [comment]
A couple things stand out:

1. Use short names like `a` for selectors (instead of `test` etc).
2. Test naming: Instead of tying tests to issue numbers, organize them based on features.

   E.g. this test should go to something like `sass-spec/string-functions/str-{slice,index,insert}.hrx` and within the HRX the tests should be named something like `quotes/input.scss`.

**Comment by nex3** [comment]
Exactly (see [DO use single-letter names for irrelevant placeholders](https://github.com/sass/sass-spec/blob/master/STYLE_GUIDE.md#do-use-single-letter-names-for-irrelevant-placeholders), [DO organize specs by which part of the language they test](https://github.com/sass/sass-spec/blob/master/STYLE_GUIDE.md#do-organize-specs-by-which-part-of-the-language-they-test), and [DO use descriptive paths](https://github.com/sass/sass-spec/blob/master/STYLE_GUIDE.md#do-use-descriptive-paths)). [DO test only one thing per spec](https://github.com/sass/sass-spec/blob/master/STYLE_GUIDE.md#do-test-only-one-thing-per-spec) is also relevant.

**Pull request merged**
