### PR TITLE
Add missing todo spec tests for issue 1219

### PR DESCRIPTION
**Pull request by mgreter**
https://github.com/sass/libsass/issues/1219

### CODE REVIEW

**Comment by cvrebert** [comment]
@mgreter This doesn't seem correct to me. The issue was regarding `.sass` files and the expected behavior was "report a compilation error and die".

**Comment by cvrebert** [comment]
@mgreter Do you agree or disagree or...?

**Comment by xzyfer** [comment]
@mgreter this should be an error spec.

@cvrebert the extension doesn't matter.

**Comment by xzyfer** [comment]
Reverted this in https://github.com/sass/sass-spec/pull/421

**Pull request merged**
