### PR TITLE
Add tests for issue #1801

### PR DESCRIPTION
**Pull request by saper**
Testing for https://github.com/sass/libsass/issues/1801

Since the infinite loops keep sassc busy,
this should probably merged after fixing this.
Alternatively those tests should be run
with a limited stack size (not implemented).

### CODE REVIEW

**Comment by saper** [comment]
Travis fails because there is an embedded full path in the error message and we compare all of it.

**Comment by xzyfer** [comment]
Thanks. We'll need to work around the path issue otherwise this spec will cause CI to always fail.

**Comment by saper** [comment]
Is `simple-loop-error` passing now with the truncated error message...?

**Comment by saper** [comment]
Ah, #674 fixed it probably..?

**Comment by mgreter** [comment]
One still made some problems. Need to check later, moved it back to todo folder.
I'm in the middle of sorting it all out ...

**Comment by saper** [comment]
Will check it... It this PR I have removed the path since it was in the first line of the output. with #674 in place it should work, I just need to regenerate the case and #674 should truncate it.

**Comment by mgreter** [comment]
I'm pretty positive that I have regenerated it, but one failed nonetheless in CI (it worked locally) ...

**Pull request merged**
