### PR TITLE
Added initial tests for selector-functions

### PR DESCRIPTION
**Pull request by onedayitwillmake**
Converted from ruby-sass project

### CODE REVIEW

**Comment by xzyfer** [comment]
@onedayitwillmake incredible work! 

Please move the `selector-functions` folder into `spec/libsass-todo-issues/issue_963` instead of `spec/libsass`

**Comment by onedayitwillmake** [comment]
Good to go :)

**Comment by am11** [comment]
This is huge! :+1: :star: :tada:

**Comment by xzyfer** [comment]
Thank you!

**Pull request merged**
