### PR TITLE
Missing separator in hrx file

### PR DESCRIPTION
**Pull request by Cerdic**
Leading to a test merge of `whiteness/low` with `blackness/max` when running the test suite in https://github.com/scssphp/scssphp/

### CODE REVIEW

**Comment by Cerdic** [comment]
There are some other cases of missing separator:
https://github.com/sass/sass-spec/blob/master/spec/css/escape.hrx#L16
https://github.com/sass/sass-spec/blob/master/spec/core_functions/color/alpha.hrx#L48
https://github.com/sass/sass-spec/blob/master/spec/core_functions/color/alpha.hrx#L96
https://github.com/sass/sass-spec/blob/master/spec/css/min_max/error.hrx#L23
https://github.com/sass/sass-spec/blob/master/spec/directives/import/load.hrx#L81
https://github.com/sass/sass-spec/blob/master/spec/core_functions/color/change_color/hwb.hrx#L43
https://github.com/sass/sass-spec/blob/master/spec/directives/forward/member/visibility.hrx#L40


And this two are not clear for me, looks like two tests are merged
https://github.com/sass/sass-spec/blob/master/spec/directives/forward/member/visibility.hrx#L46
https://github.com/sass/sass-spec/blob/master/spec/directives/forward/member/visibility.hrx#L134

Or should I consider this as normal?

**Comment by nex3** [comment]
All of those examples should have separators. In the last two, the separators should go after the first `output.css` file.

At some point, I'd like to have a linter that verifies these conventions automatically, but that'll probably need to wait until after #1581 is finished.

**Comment by Cerdic** [comment]
So I completed the PR with the other missing separators now detected by our test suite.

I made a separate commit 3669c64182db8b4c662c6b86b18cb92778eff8d3 for spec/directives/forward/member/visibility.hrx file as it appears to me that separators are just misplaced in this file (and none missing at the end) and a review would be useful

**Comment by stof** [comment]
Note that our scssphp testsuite currently relies on the separator comment to separate tests, because there is no hrx reader for PHP (and we haven't made one) so we "hacked" a way to identify specs based on the convention.

**Review by nex3 — APPROVED** [review]

**Pull request merged**
