### PR TITLE
Add spec for issue 945

### PR DESCRIPTION
**Pull request by am11**
This PR adds an error spec for issue described at sass/libsass#945.

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks @am11! Our spec format has changed slightly. Use https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-issues/issue_823 as a reference.

**Comment by am11** [comment]
Ouch, I thought that only applies to the result producing specs. :)

**Comment by am11** [comment]
Rebased and re-pushed: 942a8bb2ca0d918c13252b68ddff628307783ec9.

**Comment by xzyfer** [comment]
Yeah on second thought I'm not sure how to handle this since we don't currently assert errors. I think it'll be one of those "Just trust us" cases for now :/

**Comment by saper** [comment]
Did it regress in libsass again?

https://github.com/sass/libsass/issues/945#issuecomment-141815710

**Pull request closed without merging**
