### PR TITLE
Allow specific paths to be passed to js-api-spec

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Comment by Goodwine** [comment]
Was this not possible before? I recall doing this and it would run only those tests:
```
npm run js-api-spec -- \
  --sassSassRepo $SASS_SASS_PATH \
  --sassPackage $SASS_EMBEDDED_PATH \
  js-api-spec/legacy/importer
```

**Comment by nex3** [comment]
Nope, currently it's hard-coded.

**Review by Goodwine — APPROVED** [review]

**Comment by Goodwine** [comment]
> Nope, currently it's hard-coded.

Hm, I wonder why I can filter down to specific test files (not test cases tho) with the pattern I mentioned above 🤔

**Comment by nex3** [comment]
Are you thinking of the language spec runner? Because I just tried the JS API spec runner on main and it definitely didn't restrict itself to the paths I passed on the CLI.

**Comment by Goodwine** [comment]
We figured things out offline, I was in an older version, and I guess a newer version changed things a little so the way I mentioned doesn't work anymore without this PR

**Pull request merged**
