### PR TITLE
Convert specs to HRX format

### PR DESCRIPTION
**Pull request by nex3**
For the most part, this mechanically converts all spec directories
into individual HRX files. I've also gone through some error
directories and consolidated multiple small error specs into
individual HRX files to reduce clutter.

Output style specs have not been converted, since they're slated for
deletion anyway (#1305). It also doesn't convert specs that rely on
non-UTF-8 source encodings, since HRX only supports UTF-8.

### CODE REVIEW

**Comment by glebm** [comment]
Is anyone working on an HRX crate for Rust? Would be great to have one for rsass.

**Comment by nshahan** [comment]
@nex3 Are there any directories that you would like me to specifically look over? Otherwise I will probably just spot check a few to see that they have the expected transformation.

**Comment by nex3** [comment]
@nshahan the changes in https://github.com/sass/sass-spec/pull/1340/commits/0d02dc2171e610c441895504171d8a6d840344b0 were done by hand, so those could probably use a human eye. Otherwise, spot-checking is fine.

**Comment by nex3** [comment]
@glebm I don't know of anyone working on a Rust implementation yet.

**Pull request merged**
