### PR TITLE
Add a runner for Dart Sass

### PR DESCRIPTION
**Pull request by nex3**
This adds Dart Sass-specific versions of some specs where the output is already acceptable but different than Ruby Sass, and adds TODOs for specs with broken output.

### CODE REVIEW

**Comment by nschonni** [comment]
Might want to check out #905 for the test matrix

**Comment by nex3** [comment]
What am I looking at, exactly?

**Comment by nschonni** [comment]
Allowing multiple languages & version targets in the CI process.

**Comment by nex3** [comment]
Ah, I see, that sounds good. Should I wait for that to land before I land this?

**Comment by nschonni** [comment]
I'm not sure if it's getting merged, but I thought you might want to grab stuff from it if it helps adding this in.

**Comment by nex3** [comment]
Why might it not get merged?

**Comment by nschonni** [comment]
It's just been sitting awhile with a blocked review. I guess one of the maintainers might merged it after the libsass 3.4 stuff gets finished.

**Comment by nschonni** [comment]
Unrelated to the matrix stuff, but maybe it makes sense for the rust specific stuff to go in a "spec\dart" folder like libsass

**Comment by xzyfer** [comment]
I hadn't seen the updates to  #905. Needs a couple small changes but otherwise it's good to go. I agree this should land after #905 since that removes `test_all_impl.sh`.

**Comment by nex3** [comment]
I'd prefer to keep the Dart-specific specs in adjacent directories to the originals. That's what `--interactive` mode generates, and it makes it possible to consolidate them automatically in the future if implementations converge.

**Comment by nschonni** [comment]
Fair enough

**Comment by xzyfer** [comment]
@nex3 I've merged #905 as #965. Please rebase off master and update .travis.yml as needed.

**Pull request closed without merging**
