### PR TITLE
Add error specs for nested warn, debug and error function

### PR DESCRIPTION
**Pull request by mgreter**

### CODE REVIEW

**Comment by xzyfer** [comment]
Is there a reason you didn't use the extensive set of tests for 1653?

**Comment by mgreter** [comment]
I only see one test at https://github.com/saper/sass-spec/commit/5474032c1fc803432dc54f41c3fe8a9dc3871448 ?

**Comment by xzyfer** [comment]
https://github.com/sass/sass-spec/pull/645/files as linked to from https://github.com/sass/libsass/issues/1653#issuecomment-167388771

**Comment by mgreter** [comment]
OK, haven't seen that one. From skimming I guess the nested ruleset test still is new. It was just nice to have all specific tests in one folder to test the implementation. And the more spec tests the merrier I guess.

**Pull request merged**
