### PR TITLE
Mark a reference combinator spec as ending at 3.4.

### PR DESCRIPTION
**Pull request by nex3**
Skip ruby-sass

### CODE REVIEW

**Comment by xzyfer** [comment]
It's worth noting that remove support for reference combinators with adding support for the `>>>` combinator will prevent Sass working with Angular. More details in 

https://github.com/sass/libsass/issues/2378 and https://github.com/sass/sass/issues/2266

**Comment by nex3** [comment]
According to [this Chrome platform status page](https://www.chromestatus.com/features/6750456638341120):

> Shadow-Piercing descendant combinator, '/deep/' (aka '>>>'), including '::shadow' pseudo elements, are being deprecated.

However, [the CSS Scoping 1 spec](https://drafts.csswg.org/css-scoping-1/#deep-combinator), which was updated today, still includes `>>>`. @tabatkins, can you provide some more context here? Is `>>>` deprecated or not? Is it supported in Chrome? Will it continue to be?

**Comment by tabatkins** [comment]
Deprecated in style sheets; it's no longer allowed there per spec. Still allowed in querySelector()/etc.

**Comment by nex3** [comment]
In that case, it sounds like Angular should no longer be using either `/deep/` or `>>>` in their style sheets, so we shouldn't feel obligated to support them.

**Comment by tabatkins** [comment]
Yup, exactly.

**Comment by luchillo17** [comment]
@nex3 Mind if i ask, if they remove such selectors for nested items, with what should they replace it?

**Comment by tabatkins** [comment]
Whatever they're already using to make it work in browsers other than Chrome, presumably.

**Pull request merged**
