### PR TITLE
Test alpha channel math

### PR DESCRIPTION
**Pull request by saper**
Test only for one format (normal nested format)
because we are checking only for the error message
and no normal output is produced anyway.

This also helps to avoid a situation
where Ruby Sass produces slightly different
error messages for the compressed output format.

Related-to: https://github.com/sass/sass/issues/1916
Related-to: https://github.com/sass/sass-spec/issues/627

### CODE REVIEW

**Comment by xzyfer** [comment]
Please move this to the `libsass-todo-tests` folder and not create any more `-todo` specs. They're greatly hamper discoverability.

**Comment by saper** [comment]
Sorry, it is just a subset of @mgreter tests and I didn't really intend that for merging. But I have fixed this here!

**Comment by saper** [comment]
More extensive approach: #629

**Comment by xzyfer** [comment]
This seems like the correct approach to me. I don't see the value in testing error messages for other output modes.

**Pull request merged**
