### PR TITLE
Add variable scope tests (globals and defaults)

### PR DESCRIPTION
**Pull request by mgreter**
Spec tests for feature PR https://github.com/sass/libsass/pull/986

### CODE REVIEW

**Comment by xzyfer** [comment]
FYI there is already a very thorough PR for this

**Comment by mgreter** [comment]
OK, can you give a link? I'm pretty much done by now!

**Comment by xzyfer** [comment]
https://github.com/sass/sass-spec/pull/244

**Comment by mgreter** [comment]
Just tested and all tests pass with the open PR https://github.com/sass/libsass/pull/986
Also squashed @HugoGiraudel commits into this PR so I could test them at the same time!

**Pull request merged**
